// lib/help/kpiKeys.ts
// Every numeric KPI rendered on the dashboard. Sections add to this list
// as they introduce KPIs; the registry test enforces a corresponding entry.
import type { HelpSection } from './types';

export const KPI_KEYS = [
  // LiquidityNeed (section 1)
  'maxBorrowable',
  'expectedBorrow',
  'requiredUSDM',
  'withdrawalBuffer',
  'requiredPlusBuffer',
  'liquidityFloor',
  // FXRisk (section 2)
  'oneDayMaxDrawdownP50',
  'oneDayMaxDrawdownP95',
  'expectedLiquidationVolumeP95',
  'annualizedVol',
  // LiquidityStrategy (section 3)
  'borrowAPY',
  'grossSupplyAPY',
  'netSupplyAPY',
  'supplyIncentiveAPY',
  'totalSupplyAPY',
  'borrowerIncentiveAPY',
  'netBorrowAPY',
  // LiquidityStrategy (section 3) — Phase B carry-only loop
  'netLoopAPY',
  'netLoopAPYWithIncentives',
  'effectiveLeverageStrategy',
  'loopDebtPerCollateral',
  // LiquidationDesign (section 4)
  'minProfitableLiquidation',
  'maxProfitableLiquidation',
  'recommendedPoolDepth',
  'badDebtP95USD',
  'badDebtP95Pct',
  'concurrentStressP95',
  'preLiquidationParams',
  // VaultRecommendations (section 5)
  'recommendedLLTV',
  'riskTier',
  'vaultConfigJson',
  // Utilization (section 6)
  'recommendedUTarget',
  'borrowAPYAtTarget',
  'supplierAPYAtTarget',
  'loopMargin7d',
  'distanceToKink',
  'liquidityBufferUSD',
  'stressWithdrawalUSD',
  'survivesStress',
  'looperNetAPY',
  'effectiveLeverage',
  // FX risk overlay (vol-based, no drift)
  'fxAnnualVol',
  'fxStressDrawdown30d',
  'loopSurvivesStress',
  // Utilization page sliders (inputs)
  'tvlUSDMInput',
  'stressPctOfSupplyInput',
  'hfBufferInput',
  'rTargetOverrideInput',
  'fxStressZInput',
  // SwapLiquidity (section 7) — pool state
  'spotWtryUsdm',
  'activeLiquidityScaled',
  'poolFeeTierKpi',
  // SwapLiquidity — liquidator swap
  'usdmReceived',
  'slippagePctKpi',
  'effectivePrice',
  'feePaidUSD',
  'ticksCrossed',
  // SwapLiquidity — bad-debt distribution
  'zeroBadDebtPct',
  'medianBadDebtRate',
  'p95BadDebtRate',
] as const;

export type KpiKey = (typeof KPI_KEYS)[number];

export const KPI_SECTION: Record<KpiKey, HelpSection> = {
  maxBorrowable: 'liquidity-need',
  expectedBorrow: 'liquidity-need',
  requiredUSDM: 'liquidity-need',
  withdrawalBuffer: 'liquidity-need',
  requiredPlusBuffer: 'liquidity-need',
  liquidityFloor: 'liquidity-need',
  oneDayMaxDrawdownP50: 'fx-risk',
  oneDayMaxDrawdownP95: 'fx-risk',
  expectedLiquidationVolumeP95: 'fx-risk',
  annualizedVol: 'fx-risk',
  borrowAPY: 'strategy',
  grossSupplyAPY: 'strategy',
  netSupplyAPY: 'strategy',
  supplyIncentiveAPY: 'strategy',
  totalSupplyAPY: 'strategy',
  borrowerIncentiveAPY: 'strategy',
  netBorrowAPY: 'strategy',
  netLoopAPY: 'strategy',
  netLoopAPYWithIncentives: 'strategy',
  effectiveLeverageStrategy: 'strategy',
  loopDebtPerCollateral: 'strategy',
  minProfitableLiquidation: 'liquidation',
  maxProfitableLiquidation: 'liquidation',
  recommendedPoolDepth: 'liquidation',
  badDebtP95USD: 'liquidation',
  badDebtP95Pct: 'liquidation',
  concurrentStressP95: 'liquidation',
  preLiquidationParams: 'liquidation',
  recommendedLLTV: 'vault',
  riskTier: 'vault',
  vaultConfigJson: 'vault',
  recommendedUTarget: 'utilization',
  borrowAPYAtTarget: 'utilization',
  supplierAPYAtTarget: 'utilization',
  loopMargin7d: 'utilization',
  distanceToKink: 'utilization',
  liquidityBufferUSD: 'utilization',
  stressWithdrawalUSD: 'utilization',
  survivesStress: 'utilization',
  looperNetAPY: 'utilization',
  effectiveLeverage: 'utilization',
  fxAnnualVol: 'utilization',
  fxStressDrawdown30d: 'utilization',
  loopSurvivesStress: 'utilization',
  tvlUSDMInput: 'utilization',
  stressPctOfSupplyInput: 'utilization',
  hfBufferInput: 'utilization',
  rTargetOverrideInput: 'utilization',
  fxStressZInput: 'utilization',
  spotWtryUsdm: 'swap-liquidity',
  activeLiquidityScaled: 'swap-liquidity',
  poolFeeTierKpi: 'swap-liquidity',
  usdmReceived: 'swap-liquidity',
  slippagePctKpi: 'swap-liquidity',
  effectivePrice: 'swap-liquidity',
  feePaidUSD: 'swap-liquidity',
  ticksCrossed: 'swap-liquidity',
  zeroBadDebtPct: 'swap-liquidity',
  medianBadDebtRate: 'swap-liquidity',
  p95BadDebtRate: 'swap-liquidity',
};
